# -*- coding: utf-8 -*-
"""PadronizaçãoR.r

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIHf9Rt3AzidkTFt-HkkCFl7WF0GeCXa?usp=sharing

# Apresentação:

    Padronização dos dados.

# Preparando ambiente:

**Gerando dados artificiais**
"""

# Gerando dados:
X = 2*runif(100)
Y = 4 + 3*X + runif(100)

# Visualizando os dados
plot(X, Y, col = 'blue', xlab = 'Variável Independente (x)', ylab = 'Variável Dependente (y)',
     main = 'Dados para Regressão Linear Simples', pch = 19)
grid()  # Ativar a grade

"""**Funções Utilizadas**"""

fit <- function(x,y){
  #----------------------------------------
  # Função criara para para gerar a predição
  # da Regressão e seus coeficientes.
  #----------------------------------------

  # Gerando médias:
  xbarra <- mean(x)
  ybarra <- mean(y)

  # Calculo dos coeficientes:
  ## Coeficiente Angular:
  b1 <- sum((x-xbarra)*(y-ybarra))/sum((x-xbarra)^2)

  ## Interceptor:
  b0 <- ybarra - b1*xbarra

  return(c(b0,b1))

}

reg <- function(coef, x){
  ypred = coef[1] + coef[2]*x
  return(ypred)
}

visualization <- function(x, y, predict, coeficientes, string){
  # Visualizando os dados
  plot(x, y, col = 'blue', xlab = 'Variável Independente (x)', ylab = 'Variável Dependente (y)',
       main = 'Dados para Regressão Linear Simples', pch = 19)
  grid()  # Ativar a grade
  # Adicionar a linha de regressão
  lines(x, predict, col = 'red')
  # Adicionar ponto para o intercepto
  points(0, coeficientes[1], col = 'green', pch = 19)
  # Adicionar legenda fora do gráfico
  legend(string, legend=c("Dados Observados", "Reta de Regressão", "Intercepto"),
         col=c("blue", "red", "green"), pch=c(19, NA, 19), lty=c(0, 1, 0), xpd=TRUE)
  resp <- sprintf("Coeficientes Encontrados: b0 = %.2f e b1 = %.2f", coeficientes[1], predict[2])
  print(resp)
}

"""# Testando sem padronização:"""

# Ajustando os coeficientes:
coefs <- fit(X,Y)

# Calculando a reta de regressão:
y_pred <- reg(coefs,X)

# Visualização:
visualization(X,Y,y_pred,coefs, "topleft")

"""# Testando com Padronização:"""

# Padronizando a variável Preditora:
xp <- (X - mean(X))/sd(X)

# Ajustando os coeficientes:
coefs_padro <- fit(xp,Y)

# Calculando a reta de regressão:
y_pred_padro <- reg(coefs_padro,xp)

# Visualização:
visualization(xp,Y,y_pred_padro,coefs_padro,"topleft")

